<?php

/*
    Author: David Fonseca
*/

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('reviews')->insert([
            //Para los community posts
            [
                'id' => 1,
                'title' => 'Chilling Account of World War III',
                'description' => 'A harrowing and chilling narration of how a series of misunderstandings and hasty actions triggered a devastating global war. A powerful warning about the consequences of distrust and fear.',
                'rating' => 5,
                'user_id' => 3,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'The Reign of Incompetence: Trump as North Korean Leader',
                'description' => 'A hilariously terrifying satire of an alternate world where Trump ruled North Korea with his boundless ego. A raw look into the chaos and ruin that could have occurred had Trump held absolute power.',
                'rating' => 4,
                'user_id' => 5,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Nuclear Madness of World War III',
                'description' => 'A spine-chilling tale of a global war sparked by a misunderstanding, leading to tactical nuclear strikes and rendering entire regions uninhabitable. A grim look at the darkest consequences of armed conflict.',
                'rating' => 4,
                'user_id' => 2,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Trump\'s Disaster in North Korea',
                'description' => 'A hilariously chilling chronicle of the chaos that reigned when Trump took over North Korea, renaming it and driving the country into economic ruin with his boundless ego.',
                'rating' => 3,
                'user_id' => 4,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'The Ignition of World War III',
                'description' => 'An unsettling account of how a series of seemingly minor events triggered a spiral of distrust and military actions leading the world to the brink of nuclear destruction.',
                'rating' => 5,
                'user_id' => 1,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'The Madness of "Trumptember" in North Korea',
                'description' => 'A biting satire on Trump\'s desperate attempts to boost the North Korean economy by adding a month to the calendar and naming it in his honor, with disastrous results.',
                'rating' => 4,
                'user_id' => 6,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => 'The Grim Legacy of World War III',
                'description' => 'An in-depth examination of the lasting consequences of the global war, with redesigned borders, devastated economies, and widespread distrust among nations.',
                'rating' => 5,
                'user_id' => 2,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'title' => 'The Ego Show: Trump as Supreme Leader',
                'description' => 'A scathing narrative of how Trump\'s boundless ego led him to rename North Korea, build extravagant monuments in his honor, and neglect the basic needs of his people.',
                'rating' => 3,
                'user_id' => 3,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'title' => 'The Horrors of World War III',
                'description' => 'A harrowing account of the terrible human costs of the war, with urban combat causing countless civilian casualties and the use of tactical nuclear weapons.',
                'rating' => 4,
                'user_id' => 5,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'title' => 'Trump\'s Brief and Chaotic Reign in North Korea',
                'description' => 'A biting chronicle of Trump\'s short but disastrous reign as Supreme Leader of North Korea, which led the country into economic ruin and international isolation.',
                'rating' => 4,
                'user_id' => 1,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'title' => 'The Role of Cyberwarfare in World War III',
                'description' => 'A fascinating analysis of how advances in cyber technology changed the nature of combat during the war, with hackers playing a key role on the battlefields.',
                'rating' => 5,
                'user_id' => 4,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'title' => 'The Nightmare of "Tremendous Work Resorts" by Trump',
                'description' => 'A satirical and terrifying look at the forced labor camps rebranded as "Tremendous Work Resorts" by Trump, where dissenters were sent to "re-educate".',
                'rating' => 3,
                'user_id' => 6,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'title' => 'The Peace Movement After World War III',
                'description' => 'An examination of how the horrors of war fueled a powerful global peace movement that demanded disarmament and a new form of international governance to prevent future conflicts.',
                'rating' => 4,
                'user_id' => 2,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'title' => 'The Economic Disaster of the Trump Era in North Korea',
                'description' => 'A biting analysis of how Trump\'s erratic and selfish economic policies, combined with international sanctions, led North Korea into a massive famine crisis.',
                'rating' => 3,
                'user_id' => 3,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'title' => 'The Enduring Scars of World War III',
                'description' => 'A poignant exploration of the lasting impact of the war on the minds and spirits of survivors, and how the psychological aftermath lingers long after hostilities have ceased.',
                'rating' => 5,
                'user_id' => 5,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'title' => 'The Joke That Went Too Far: Trump in North Korea',
                'description' => 'A scathing satire on how Trump\'s appointment as Supreme Leader of North Korea, initially thought to be a joke, quickly turned into a disaster of epic proportions.',
                'rating' => 4,
                'user_id' => 1,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'title' => 'Chronicle of the Spiral into World War III',
                'description' => 'A terrifying recount of how a series of misunderstandings, unfounded accusations, and chain reactions brought the world to the brink of total nuclear war.',
                'rating' => 5,
                'user_id' => 4,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'title' => 'The PR Disaster of the Trump Era in North Korea',
                'description' => 'A satirical look at how constant self-promotion and social media gaffes turned Trump\'s reign in North Korea into an international laughingstock.',
                'rating' => 4,
                'user_id' => 6,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'title' => 'The Lessons of World War III',
                'description' => 'An insightful analysis of the lessons that can be learned from the horrors of war, highlighting the importance of dialogue, mutual understanding, and diplomacy in preventing future conflicts.',
                'rating' => 5,
                'user_id' => 2,
                'travel_id' => null,
                'community_post_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'title' => 'Trump\'s Coup Attempt in North Korea',
                'description' => 'A hilarious and terrifying account of Trump\'s desperate attempt to cling to power in North Korea, demanding access to nuclear weapons before being dragged out by his iconic hair.',
                'rating' => 4,
                'user_id' => 3,
                'travel_id' => null,
                'community_post_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Para los travels
            [
                'id' => 21,
                'title' => 'A Monumental Journey to the Past',
                'description' => 'Breathtaking experience witnessing the construction of the pyramids. A journey through time!',
                'rating' => 5,
                'user_id' => 1,
                'travel_id' => 1,
                'community_post_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'title' => 'Witnessing History: The Pyramids of Giza',
                'description' => 'Fascinating to see these colossal structures rise. An unforgettable journey.',
                'rating' => 4,
                'user_id' => 2,
                'travel_id' => 1,
                'community_post_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'title' => 'Hard Work for an Eternal Legacy',
                'description' => 'Impressive engineering and human effort behind the pyramids. A journey that makes you reflect.',
                'rating' => 5,
                'user_id' => 3,
                'travel_id' => 1,
                'community_post_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'title' => 'An Epic Journey: Following in Columbus\'s Footsteps',
                'description' => 'Exciting experience sailing across the Atlantic and reaching the Americas. A journey that changed the world!',
                'rating' => 5,
                'user_id' => 4,
                'travel_id' => 2,
                'community_post_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'title' => 'An Encounter of Cultures: The Clash of Two Worlds',
                'description' => 'Fascinating to see how two vastly different cultures met. A journey that broadens your mind.',
                'rating' => 4,
                'user_id' => 5,
                'travel_id' => 2,
                'community_post_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'title' => 'A Journey of Hope: Towards a New World',
                'description' => 'Exciting journey filled with hope and dreams. A journey that inspires you.',
                'rating' => 5,
                'user_id' => 6,
                'travel_id' => 2,
                'community_post_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
